#!/usr/bin/env bash
# This script parses an Apache log access file by ip address using awk.
file_name="apache-access.log"
if test -f $file_name; then
  awk '{print $1,$9}' $file_name | sort | uniq -c | sort -gr
fi