#!/usr/bin/env bash
# This script displays "bad luck from China" on loop 4.
# "bad luck from Japan" on loop 9.
# "bad luck from Italy on loop 17.
# Also displays a counter from 1 to 20 on every line.
i=0
while [[ $i -lt 20 ]]; do
  case "$i" in
    "3")
      echo -e "4\nbad luck from China"
      ;;
    "8")
      echo -e "9\nbad luck from Japan"
      ;;
    "16")
      echo -e "17\nbad luck from Italy"
      ;;
    *)
    echo "$((i + 1))"
  esac
  i="$((i + 1))"
done
